### ISSUE TITLE
Debug adapter process has terminated unexpectedly (read error)

### ISSUE THREAD

**Issue by mzafrany** [raix/vscode-perl-debug#47]
Hi,
I'm getting the following message "Debug adapter process has terminated unexpectedly (read error)"
when pressing F5.
I've notice the following over the output extensions terminal
Appreciate your help

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at StreamCatcher.nextRequest (c:\Users\mzafrany\.vscode\extensions\mortenhenriksen.perl-debug-0.4.1\out\streamCatcher.js:119:28)
    at StreamCatcher.resolveRequest (c:\Users\mzafrany\.vscode\extensions\mortenhenriksen.perl-debug-0.4.1\out\streamCatcher.js:109:14)
    at StreamCatcher.readline (c:\Users\mzafrany\.vscode\extensions\mortenhenriksen.perl-debug-0.4.1\out\streamCatcher.js:95:18)
    at Socket.<anonymous> (c:\Users\mzafrany\.vscode\extensions\mortenhenriksen.perl-debug-0.4.1\out\streamCatcher.js:79:23)
    at emitOne (events.js:121:20)    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by mzafrany** [comment]
restart of the PC resolved the problem
